Repository softeerbootcamp-3rd/Team9-HexaCore, pull requests merged in 2024-02, with the labels that each got.

#10 [FE/BE] #9: 리드미 프로젝트 소개, 그라운드 룰, 개발 컨벤션, 기획/디자인 문서 정리
  README.md
Labels: docs

#11 [FE] #7: 공통 화면 제작, 폴더 구조 변경
  client/public/Tayo-logo.png
  client/src/App.tsx
  client/src/components/Button.tsx
  client/src/components/Header.tsx
  client/src/components/svgs/Envelope.tsx
  client/src/components/svgs/UserCircle.tsx
  client/src/main.tsx
  client/src/pages/CarDetail.tsx
  client/src/pages/Home.tsx
  client/src/pages/HostManage.tsx
  client/src/pages/HostRegister.tsx
  client/src/pages/Profile.tsx
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/cars/carRoutes.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/homeRoutes.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/HostRegister.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
  client/tailwind.config.js
Labels: FE, feat

#19 [FE] #18: 모든 페이지의 main 최소 전체 화면으로 수정
  client/src/App.tsx
Labels: FE, feat

#21 [BE] #12: 응답 형태 통일을 위한 기본 세팅
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/common/DataResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/PageInfoDto.java
  server/src/main/java/com/hexacore/tayo/common/PageResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/ResponseCode.java
  server/src/main/java/com/hexacore/tayo/common/ResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
  server/src/main/java/com/hexacore/tayo/common/errors/GeneralException.java
  server/src/main/java/com/hexacore/tayo/test/TestController.java
  server/src/main/java/com/hexacore/tayo/test/TestService.java
  server/src/main/java/com/hexacore/tayo/test/model/TestDto.java
Labels: BE, discussion

#22 [FE] #18: 페이지가 최대 회면을 넘어갔을 때 배경은 늘어나지 않는 버그 수정
  client/src/App.tsx
Labels: bug, FE

#25 [BE] 데이터베이스 세팅 & 기본 엔티티 생성
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/TayoApplication.java
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/ModelRepository.java
  server/src/main/java/com/hexacore/tayo/car/model/CarEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/CarType.java
  server/src/main/java/com/hexacore/tayo/car/model/ImageEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/ModelEntity.java
  server/src/main/java/com/hexacore/tayo/common/BaseTime.java
  server/src/main/java/com/hexacore/tayo/reservation/model/ReservationEntity.java
  server/src/main/java/com/hexacore/tayo/reservation/model/ReservationStatus.java
  server/src/main/java/com/hexacore/tayo/user/model/UserEntity.java
  server/src/main/resources/application.properties
Labels: BE, discussion

#32 [FE] #13: 로그인, 회원가입 화면 구현
  client/public/defaultProfile.png
  client/src/main.tsx
  client/src/pages/auth/InputBox.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/pages/auth/authRoutes.tsx
Labels: FE, feat

#35 [BE] #23: 백엔드 서버 배포 파이프라인 구축
  .github/workflows/be-gradle.yml
  server/Dockerfile
Labels: BE, feat

#34 [BE] 차량 예약 가능 날짜 수정 api 구현
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/CarEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/DateListDto.java
  server/src/main/java/com/hexacore/tayo/common/ResponseCode.java
Labels: BE, feat

#30 [FE] #15 : 호스트 페이지 개발
  client/src/components/Tag.tsx
  client/src/pages/hosts/CarData.json
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
Labels: FE, feat

#33 [FE] #31 : 마이 페이지 개발
  client/public/default-profile.png
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/dummy.json
  client/src/pages/profile/profileRoutes.tsx
Labels: FE, feat

#43 [BE] #40 ResponseCode를 ErrorCode로 수정
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/common/DataResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/PageResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/ResponseCode.java
  server/src/main/java/com/hexacore/tayo/common/ResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
  server/src/main/java/com/hexacore/tayo/common/errors/GeneralException.java
  server/src/main/java/com/hexacore/tayo/test/TestController.java
  server/src/main/java/com/hexacore/tayo/test/TestService.java
Labels: BE

#38 [FE] #17: 차량 등록 페이지 구현
  client/public/form-image-add.png
  client/public/search-button.png
  client/src/pages/hosts/HostRegister.tsx
  client/src/pages/hosts/ImageUploadButton.tsx
Labels: FE, feat

#42 [BE] #36: 차량 삭제, 등록 및 세부 모델 조회 API
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/ImageRepository.java
  server/src/main/java/com/hexacore/tayo/car/ModelRepository.java
  server/src/main/java/com/hexacore/tayo/car/model/CarEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/CategoryDto.java
  server/src/main/java/com/hexacore/tayo/car/model/CategoryListDto.java
  server/src/main/java/com/hexacore/tayo/car/model/ImageEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/PositionDto.java
  server/src/main/java/com/hexacore/tayo/car/model/PostCarDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/config/S3Config.java
  server/src/main/java/com/hexacore/tayo/user/model/UserEntity.java
Labels: BE, feat

#44 [FE] 호스트 페이지 UI 수정
  client/src/pages/hosts/CarData.json
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
Labels: FE

#50 [FE] #46: 타입, 경로, react hook 잘못 사용한 부분 등 오류 수정, 차량 등록 화면 페이지 레이아웃 수정
  client/src/components/TitledBlock.tsx
  client/src/pages/hosts/HostRegister.tsx
  client/src/pages/hosts/ImageUploadButton.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
Labels: bug, FE, feat

#49 [BE] #45: 파일 업로드 크기 20BM로 제한
  server/src/main/resources/application.properties
Labels: bug, BE

#57 [FE] #24: 메인 검색 화면 구현
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/components/svgs/MainCar.tsx
  client/src/components/svgs/Search.tsx
  client/src/pages/home/CarCard.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/Map.tsx
  client/src/pages/home/MultipleSelect.tsx
  client/src/pages/home/SearchBar.tsx
  client/src/pages/home/SelectCarType.tsx
  client/src/pages/home/SideBar.tsx
  client/src/pages/home/SingleSelect.tsx
  client/src/pages/home/dummy/cars.json
  client/src/pages/home/dummy/category.json
  client/src/pages/home/homeRoutes.tsx
  client/src/pages/hosts/HostRegister.tsx
  client/tailwind.config.js
Labels: FE, feat

#60 [FE] #16: 캘린더 컴포넌트 생성, 호스트 예약 관리 페이지에 달력 추가
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Button.tsx
  client/src/components/Header.tsx
  client/src/components/calendar/CalendarDate.tsx
  client/src/components/calendar/CalendarDay.tsx
  client/src/components/calendar/calendar.core.ts
  client/src/components/calendar/guestCalendar/GuestCalendar.tsx
  client/src/components/calendar/guestCalendar/calendar.guest.ts
  client/src/components/calendar/hostCalendar/HostCalendar.tsx
  client/src/components/calendar/hostCalendar/HostCalendarDate.tsx
  client/src/components/calendar/hostCalendar/calendar.host.ts
  client/src/components/svgs/ChevronLeft.tsx
  client/src/components/svgs/ChevronRight.tsx
  client/src/components/svgs/Envelope.tsx
  client/src/components/svgs/UserCircle.tsx
  client/src/fetches/cars/CarDetail.dummy.json
  client/src/fetches/cars/fetchCarDetail.ts
  client/src/fetches/reservations/HostReservationData.dummy.json
  client/src/fetches/reservations/fetchHostReservations.ts
  client/src/pages/auth/InputBox.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/utils/converters.ts
Labels: FE, feat

#65 [BE] #64: MethodArgumentNotValidException 예외처리 추가
  server/src/main/java/com/hexacore/tayo/common/ResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
Labels: BE, feat

#68 [BE] #61: 차량 등록, 삭제, 세부 모델 조회 API - 테스트 코드 작성
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/ModelEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/PostCarDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/user/UserRepository.java
  server/src/test/java/com/hexacore/tayo/car/CarControllerTest.java
  server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceGetCategoriesTest.java
  server/src/test/java/com/hexacore/tayo/car/ModelRepositoryTest.java
Labels: BE, test

#76 [BE] #66: 로거 커스터마이징
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/auth/JwtService.java
  server/src/main/java/com/hexacore/tayo/auth/RefreshTokenRepository.java
  server/src/main/java/com/hexacore/tayo/auth/interceptor/AuthenticationInterceptor.java
  server/src/main/java/com/hexacore/tayo/auth/interceptor/RefreshAccessTokenInterceptor.java
  server/src/main/java/com/hexacore/tayo/auth/interceptor/RequestParser.java
  server/src/main/java/com/hexacore/tayo/auth/model/RefreshTokenEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/AuthException.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/config/InterceptorConfig.java
  server/src/main/java/com/hexacore/tayo/log/LogTestController.java
  server/src/main/java/com/hexacore/tayo/log/LoggingAspect.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserRepository.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/dto/LoginRequestDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/LoginResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/SignUpRequestDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/UserSimpleDto.java
  server/src/main/java/com/hexacore/tayo/user/model/UserEntity.java
  server/src/main/resources/application.properties
  server/src/main/resources/log4j2.xml
  server/src/test/.DS_Store
Labels: BE

#73 [FE] #56: 리스트 컴포넌트 개발 & 호스트 페이지/마이 페이지 리팩토링
  client/src/components/Button.tsx
  client/src/components/ListComponent.tsx
  client/src/fetches/reservations/fetchHostReservations.ts
  client/src/fetches/users/fetchUser.ts
  client/src/fetches/users/userData.dummy.json
  client/src/pages/hosts/CarReservationData.json
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/UserReservationData.json
  client/src/pages/profile/profileRoutes.tsx
Labels: FE, feat

#75 [BE] #69: 유저 회원가입, 수정, 조회, 로그아웃 api 구현
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/auth/AuthController.java
  server/src/main/java/com/hexacore/tayo/auth/AuthService.java
  server/src/main/java/com/hexacore/tayo/auth/JwtService.java
  server/src/main/java/com/hexacore/tayo/auth/RefreshTokenRepository.java
  server/src/main/java/com/hexacore/tayo/auth/interceptor/AuthenticationInterceptor.java
  server/src/main/java/com/hexacore/tayo/auth/interceptor/RefreshAccessTokenInterceptor.java
  server/src/main/java/com/hexacore/tayo/auth/jwt/JwtParser.java
  server/src/main/java/com/hexacore/tayo/auth/jwt/JwtProvider.java
  server/src/main/java/com/hexacore/tayo/auth/refresh/RefreshToken.java
  server/src/main/java/com/hexacore/tayo/auth/refresh/RefreshTokenRepository.java
  server/src/main/java/com/hexacore/tayo/auth/refresh/RefreshTokenService.java
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/CarEntity.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/config/InterceptorConfig.java
  server/src/main/java/com/hexacore/tayo/image/S3Manager.java
  server/src/main/java/com/hexacore/tayo/log/LoggingAspect.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/dto/LoginResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/UpdateUserRequestDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/UserInfoResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/UserSimpleDto.java
  server/src/main/java/com/hexacore/tayo/user/model/UserEntity.java
  server/src/main/java/com/hexacore/tayo/util/Encryptor.java
  server/src/main/java/com/hexacore/tayo/util/RequestParser.java
Labels: BE, feat

#63 [BE] #62: 예약 가능한 날짜 수정 api 테스트코드 작성
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateDatesTest.java
Labels: BE, test

#70 [BE] #14: 차량 예약 관련 API
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDto.java
  server/src/main/java/com/hexacore/tayo/car/model/CarEntity.java
  server/src/main/java/com/hexacore/tayo/car/model/DateListDto.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationRepository.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/CreateReservationRequestDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationsResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationsResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/model/Guest.java
  server/src/main/java/com/hexacore/tayo/reservation/model/GuestReservation.java
  server/src/main/java/com/hexacore/tayo/reservation/model/HostCar.java
  server/src/main/java/com/hexacore/tayo/reservation/model/HostReservation.java
  server/src/main/java/com/hexacore/tayo/reservation/model/ReservationEntity.java
  server/src/test/.DS_Store
Labels: BE, feat

#83 [BE] #72: HTTP 공통 응답 형식 refactoring
  server/src/main/java/com/hexacore/tayo/auth/AuthController.java
  server/src/main/java/com/hexacore/tayo/auth/AuthService.java
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/category/model/Category.java
  server/src/main/java/com/hexacore/tayo/category/model/SubCategory.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
  server/src/main/java/com/hexacore/tayo/common/response/DataResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/response/PageInfo.java
  server/src/main/java/com/hexacore/tayo/common/response/PageResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/response/Response.java
  server/src/main/java/com/hexacore/tayo/common/response/ResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/model/Reservation.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
Labels: BE, refactor

#84 [BE] #72: Status에 대한 응답 반환 형태 수정
  server/src/main/java/com/hexacore/tayo/common/response/Response.java
Labels: bug, BE

#94 [FE] #82: Ajax 요청 통합 처리 함수 제작
  client/.env.example
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/fetches/common/axios.ts
  client/src/fetches/common/response.type.ts
Labels: FE, feat

#95 [BE] #88: 차량 등록, 삭제, 카테고리 조회 API 수정
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/car/model/FuelType.java
  server/src/main/java/com/hexacore/tayo/category/CategoryController.java
  server/src/main/java/com/hexacore/tayo/category/CategoryService.java
  server/src/main/java/com/hexacore/tayo/category/dto/GetCategoriesResponseDto.java
  server/src/main/java/com/hexacore/tayo/category/dto/GetSubCategoryListResponseDto.java
  server/src/main/java/com/hexacore/tayo/category/dto/GetSubCategoryResponseDto.java
  server/src/main/java/com/hexacore/tayo/category/model/SubCategory.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/util/S3Manager.java
  server/src/test/java/com/hexacore/tayo/car/CarControllerTest.java
  server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceGetCategoriesTest.java
  server/src/test/java/com/hexacore/tayo/category/CategoryServiceTest.java
Labels: BE, refactor

#96 [BE] #89: 차량 예약 관련 API 변경사항 적용
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarDateRangeRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetDateListRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDateRange.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/CreateReservationRequestDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/model/Reservation.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateDatesTest.java
Labels: BE, feat

#92 [BE] #85: 토큰 만료, 유효하지 않은 토큰 상태 코드 다르게 수정, 인증 버그 해결
  server/src/main/java/com/hexacore/tayo/auth/AuthController.java
  server/src/main/java/com/hexacore/tayo/auth/jwt/util/JwtParser.java
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/common/UriPath.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/config/InterceptorConfig.java
  server/src/main/java/com/hexacore/tayo/config/WebConfig.java
  server/src/main/java/com/hexacore/tayo/interceptor/AuthenticationInterceptor.java
  server/src/main/java/com/hexacore/tayo/interceptor/RefreshAccessTokenInterceptor.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserRepository.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceGetCategoriesTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateDatesTest.java
Labels: bug, BE, refactor

#103 [BE] #90 차량 조회 수정 API 리팩토링
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/model/CarType.java
  server/src/main/java/com/hexacore/tayo/car/model/FuelType.java
  server/src/main/java/com/hexacore/tayo/config/InterceptorConfig.java
  server/src/main/java/com/hexacore/tayo/user/dto/GetUserSimpleResponseDto.java
Labels: BE, feat, refactor

#102 [FE] #100: 로그인, 회원가입 api 연동
  client/src/pages/auth/InputBox.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
Labels: FE, feat

#104 [BE] #97 차량 조회/수정 test 코드 작성
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeResponseDto.java
  server/src/test/java/com/hexacore/tayo/car/CarControllerTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceRetrieveCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/carDetailTest.java
Labels: BE, test

#107 [BE] #101: CarDateRange 관련 수정
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarDateRangeRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDateRange.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateDatesTest.java
Labels: bug, BE

#112 [BE] #55: 차량 검색 기능 구현
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/CarSpecifications.java
  server/src/main/java/com/hexacore/tayo/car/dto/CreateCarRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsParamsDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDateRange.java
  server/src/main/java/com/hexacore/tayo/category/CategoryService.java
  server/src/main/java/com/hexacore/tayo/category/SubcategoryRepository.java
  server/src/main/java/com/hexacore/tayo/category/dto/GetCategoriesResponseDto.java
  server/src/main/java/com/hexacore/tayo/category/model/Subcategory.java
  server/src/main/java/com/hexacore/tayo/common/Position.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
  server/src/main/java/com/hexacore/tayo/common/response/Response.java
  server/src/main/java/com/hexacore/tayo/interceptor/AuthenticationInterceptor.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
Labels: BE, feat

#116 [FE, BE] #110: jwt 토큰을 로컬 스토리지에 저장하도록 수정
  client/src/fetches/auth/auth.type.ts
  client/src/fetches/common/axios.ts
  client/src/pages/auth/Login.tsx
  server/src/main/java/com/hexacore/tayo/auth/AuthController.java
  server/src/main/java/com/hexacore/tayo/auth/AuthService.java
  server/src/main/java/com/hexacore/tayo/auth/jwt/dto/GetTokenResponseDto.java
  server/src/main/java/com/hexacore/tayo/config/InterceptorConfig.java
  server/src/main/java/com/hexacore/tayo/interceptor/AuthenticationInterceptor.java
  server/src/main/java/com/hexacore/tayo/user/dto/LoginResponseDto.java
  server/src/main/java/com/hexacore/tayo/util/RequestParser.java
Labels: bug, FE, BE

#126 [BE] #125: 예약 정보 업데이트 시 validation 버그 수정
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: bug, BE

#121 [FE] #111프론트엔드 배포 파이프라인 구축
  .github/workflows/fe-vite.yml
  client/package.json
Labels: FE

#123 [FE] #24: 홈 화면 구현 - API 연결
  client/src/fetches/cars/cars.type.ts
  client/src/fetches/cars/fetchCars.ts
  client/src/fetches/categories/categories.type.ts
  client/src/fetches/categories/fetchCategories.ts
  client/src/pages/home/CarCard.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/Map.tsx
  client/src/pages/home/MultipleSelect.tsx
  client/src/pages/home/SearchBar.tsx
  client/src/pages/home/SelectCarType.tsx
  client/src/pages/home/SideBar.tsx
  client/src/pages/home/SingleSelect.tsx
  client/src/pages/home/dummy/cars.json
  client/src/pages/home/dummy/categories.json
  client/src/pages/home/dummy/category.json
  client/src/pages/home/homeRoutes.tsx
  client/src/utils/converters.ts
Labels: FE, feat

#120 [BE] #88: 차량 등록, 삭제, 카테고리 조회 API 수정
  server/src/main/java/com/hexacore/tayo/category/CategoryController.java
  server/src/main/java/com/hexacore/tayo/category/CategoryService.java
  server/src/main/java/com/hexacore/tayo/category/dto/GetCategoriesResponseDto.java
  server/src/main/java/com/hexacore/tayo/category/model/Category.java
  server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceGetCategoriesTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceRetrieveCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CategoryRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/category/CategoryServiceTest.java
Labels: BE, refactor

#117 [BE] #109: 회원가입 api 검증 로직 추가
  client/src/components/InputBox.tsx
  client/src/components/ListComponent.tsx
  client/src/fetches/users/fetchUser.ts
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/profileRoutes.tsx
  server/src/main/java/com/hexacore/tayo/auth/AuthController.java
  server/src/main/java/com/hexacore/tayo/user/dto/LoginRequestDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/SignUpRequestDto.java
Labels: BE, feat

#119 [BE] #118: 인터셉터 허용 메소드, 경로 추가
  server/src/main/java/com/hexacore/tayo/interceptor/AuthenticationInterceptor.java
Labels: bug, BE, urgent

#132 [BE] 검색 API 버그 수정
  server/src/main/java/com/hexacore/tayo/car/CarSpecifications.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
  server/src/main/java/com/hexacore/tayo/common/Position.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
Labels: bug, BE

#124 [BE] #122 차량 예약 가능 날짜 데이터 조회 로직 수정
  server/src/main/java/com/hexacore/tayo/car/CarSpecifications.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: bug, BE

#113 [BE] #108: ERD 수정으로 인한 연관관계 변경 및 예외 추가
  server/src/main/java/com/hexacore/tayo/car/CarDateRangeRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDateRange.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationRepository.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/CreateReservationRequestDto.java
  server/src/main/java/com/hexacore/tayo/reservation/model/Reservation.java
Labels: BE, feat

#133 [FE] 호스트 #106 페이지 API 연동
  client/src/components/ListComponent.tsx
  client/src/fetches/cars/HostReservationData.dummy.json
  client/src/fetches/cars/fetchCarDetail.ts
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
Labels: FE, BE, feat

#139 [BE] #135: User 엔티티 클래스에서 Car 와 One-To-One 매핑 처리 문제
  server/src/main/java/com/hexacore/tayo/auth/AuthService.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
Labels: bug, BE

#141 [FE] #140: 검색 화면에서 검색 결과를 받아오지 못하는 경우 에러 발생
  client/src/pages/home/Home.tsx
Labels: bug, FE

#142 [BE] #138: DB 변경사항 반영하여 차량 삭제 API 수정
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
Labels: BE, refactor

#150 [FE] #127 마이페이지 API 연동
  client/src/components/ListComponent.tsx
  client/src/fetches/reservations/Reservation.type.ts
  client/src/fetches/users/fetchUser.ts
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/UpdateReservationStatusRequestDto.java
  server/src/main/java/com/hexacore/tayo/reservation/model/ReservationStatus.java
Labels: bug, FE, feat

#154 [BE] #153 image 삭제 방식 변경에 따른 차량 수정 API 수정
  server/src/main/java/com/hexacore/tayo/car/CarImageRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/CarImage.java
Labels: bug, BE

#143 [FE] #115: 차량번호로 차량 조회 및 주소 API 적용
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/components/ListComponent.tsx
  client/src/pages/hosts/AddressButton.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/HostRegister.tsx
  client/src/pages/hosts/ImageUploadButton.tsx
  client/src/pages/hosts/hostsRoutes.tsx
Labels: FE, feat

#152 [FE] #149: 차량 상세 정보 페이지에서 마이페이지로 리다이렉팅
  client/src/components/ImageGallery.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
Labels: FE, feat

#158 [BE] #157: 예약 가능 날짜 업데이트 API 버그 수정
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
Labels: bug, BE

#169 [FE, BE] #147: 로그아웃, 회원 탈퇴 api 연결 - 회원 탈퇴 api 수정
  client/src/components/Header.tsx
  client/src/components/svgs/MailIcon.tsx
  client/src/components/svgs/PhoneIcon.tsx
  client/src/fetches/auth/fetchAuth.ts
  client/src/fetches/common/axios.ts
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/SignUp.tsx
  client/src/pages/profile/Profile.tsx
  server/src/main/java/com/hexacore/tayo/auth/AuthController.java
  server/src/main/java/com/hexacore/tayo/auth/AuthService.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/user/UserRepository.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
Labels: FE, BE, feat

#172 [FE] #170 호스트 페이지 & 게스트 페이지 버그 수정
  client/src/components/ListComponent.tsx
  client/src/fetches/reservations/Reservation.type.ts
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
Labels: FE, refactor

#168 [BE] #167: 응답 dto에 toString() 메소드 추가
  server/src/main/java/com/hexacore/tayo/auth/jwt/dto/GetTokenResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
  server/src/main/java/com/hexacore/tayo/category/dto/GetCategoriesResponseDto.java
  server/src/main/java/com/hexacore/tayo/common/response/Response.java
  server/src/main/java/com/hexacore/tayo/interceptor/LoggingInterceptor.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetCarSimpleResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationListResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationListResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/GetUserInfoResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/GetUserSimpleResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/LoginResponseDto.java
Labels: bug, BE

#178 [FE] #177: 대여시각과 반납시각이 일치할 경우 예약하지 못 하도록 수정
  client/src/pages/cars/CarDetail.tsx
Labels: bug, FE

#185 [BE] #137: 수정된 예약, 예약 가능 날짜 DB 테이블에 맞춰 검색 API 수정
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarCustomRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarCustomRepositoryImpl.java
  server/src/main/java/com/hexacore/tayo/car/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/CarSpecifications.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsParamsDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
  server/src/main/java/com/hexacore/tayo/common/Position.java
  server/src/main/java/com/hexacore/tayo/common/response/PageInfo.java
  server/src/main/java/com/hexacore/tayo/common/response/Response.java
  server/src/main/java/com/hexacore/tayo/config/QueryDslConfig.java
Labels: BE, refactor

#180 [FE, BE] #162: 결제 모듈 추가
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/components/Toast.tsx
  client/src/fetches/users/fetchUser.ts
  client/src/fetches/users/users.type.ts
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/cars/Payment.tsx
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/common/errors/GeneralException.java
  server/src/main/java/com/hexacore/tayo/config/AppConfig.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/TossPayment.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserRepository.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/dto/GetUserCustomerKeyResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
Labels: FE, BE, feat

#191 [FE] #188: 검색 API 수정에 따른 프론트 수정
  client/src/fetches/cars/cars.type.ts
  client/src/fetches/cars/fetchCars.ts
  client/src/fetches/categories/fetchCategories.ts
  client/src/fetches/common/response.type.ts
  client/src/pages/home/CarCard.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/homeRoutes.tsx
Labels: FE, refactor

#182 [BE] #176: 차량 삭제 시 연결된 car_date_range 하드 딜리트
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
Labels: bug, BE

#173 [BE] #161: soft delete 한 데이터가 조회될 수 있는 이슈
  server/src/main/java/com/hexacore/tayo/car/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: bug, BE

#194 [BE] #193: toString() 메서드 중복 에러
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsResultDto.java
Labels: bug, BE, urgent

#196 [FE, BE] 결제 모듈 에러 수정
  client/src/fetches/users/fetchUser.ts
  client/src/pages/cars/Payment.tsx
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: bug, FE, BE

#199 [BE] #195: 호스트 차량 정보 조회 api 수정
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
Labels: bug, BE

#200 [FE] #183: 차량 등록/수정 페이지 관련 수정
  client/src/pages/hosts/HostRegister.tsx
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
Labels: FE, feat

#175 [BE] #171: 예약 조회시마다 예약 상태 업데이트하도록 변경 및 수정사항 반영
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationRepository.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetCarSimpleResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationListResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationListResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetHostReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/model/Reservation.java
  server/src/main/java/com/hexacore/tayo/reservation/model/ReservationStatus.java
Labels: BE, feat

#197 [FE] #186: context API와 localstorage를 이용한 로그인 정보 전역 관리
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/contexts/AuthContext.tsx
  client/src/fetches/auth/fetchAuth.ts
  client/src/fetches/common/axios.ts
  client/src/pages/auth/Login.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
Labels: FE, feat

#204 [BE] #203: FuelType과 CarType에서 NOT_FOUND 삭제
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/model/CarType.java
  server/src/main/java/com/hexacore/tayo/car/model/FuelType.java
Labels: bug, BE

#187 [FE] #174 유저정보 수정 API 연결
  client/src/pages/auth/SignUp.tsx
  client/src/pages/auth/authRoutes.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
  server/src/main/java/com/hexacore/tayo/user/UserService.java
Labels: FE, feat

#209 [FE] #190: 예약 상태 변경 방식 변경
  client/src/components/ListComponent.tsx
  client/src/components/timer.tsx
  client/src/fetches/reservations/Reservation.type.ts
  client/src/fetches/reservations/fetchGuestReservations.ts
  client/src/fetches/reservations/fetchHostReservations.ts
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
  client/src/utils/DistanceCalculater.ts
  client/src/utils/converters.ts
  client/tailwind.config.js
  server/src/main/java/com/hexacore/tayo/reservation/dto/GetGuestReservationResponseDto.java
Labels: FE, feat

#214 hotfix : scrolle hide import 오류
  client/package-lock.json
  client/package.json
  client/src/components/timer.tsx
Labels: urgent

#215 [FE] !HOTFIX: 날짜 서버로 전송 시 타임존 이슈
  client/src/fetches/reservations/fetchHostReservations.ts
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/utils/converters.ts
Labels: bug, FE

#206 [BE] #205: SearchCarsDto에서 type이 null일 경우 CarType enum을 사용하지 않음
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsDto.java
Labels: bug, BE

#216 [BE] #90 : 차량 조회 수정 API 리팩토링
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarRequestDto.java
Labels: BE, feat

#218 [FE] #192: 예약 상태 플로우 변경
  client/index.html
  client/src/components/PaymentModal.tsx
  client/src/fetches/users/fetchUser.ts
  client/src/fetches/users/users.type.ts
  client/src/main.tsx
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/payment/Payment.tsx
  client/src/pages/payment/PaymentIsPending.tsx
  client/src/pages/payment/paymentRoutes.tsx
  client/tailwind.config.js
Labels: FE, feat

#217 [BE] #192: 예약 상태 플로우 변경
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorExceptionHandler.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/CreateReservationResponseDto.java
  server/src/main/java/com/hexacore/tayo/reservation/model/Reservation.java
  server/src/main/java/com/hexacore/tayo/user/UserController.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/dto/GetUserCustomerKeyResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/GetUserPaymentInfoResponseDto.java
  server/src/main/java/com/hexacore/tayo/user/dto/UpdateUserBillingKeyRequestDto.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
  server/src/main/java/com/hexacore/tayo/util/payment/PaymentManager.java
  server/src/main/java/com/hexacore/tayo/util/payment/TossPaymentDto.java
Labels: BE, feat

#212 [BE] #201: SSE 서버 구현
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/config/WebConfig.java
  server/src/main/java/com/hexacore/tayo/notification/NotificationController.java
  server/src/main/java/com/hexacore/tayo/notification/NotificationManager.java
  server/src/main/java/com/hexacore/tayo/notification/NotificationRepository.java
  server/src/main/java/com/hexacore/tayo/notification/NotificationService.java
  server/src/main/java/com/hexacore/tayo/notification/dto/SseNotificationDto.java
  server/src/main/java/com/hexacore/tayo/notification/model/Notification.java
  server/src/main/java/com/hexacore/tayo/notification/model/NotificationType.java
  server/src/main/java/com/hexacore/tayo/notification/sse/SseEmitterRepository.java
  server/src/main/java/com/hexacore/tayo/notification/sse/SseEmitterService.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: BE, feat

#228 [BE] !hotfix: dev merge 오류 해결
  server/src/main/java/com/hexacore/tayo/notification/manager/NotificationManager.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/reservation/dto/CreateReservationResponseDto.java
Labels: bug, BE

#189 [BE] #164: 게스트/차량 리뷰 등록 및 조회 api 구현
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/interceptor/LoggingInterceptor.java
  server/src/main/java/com/hexacore/tayo/review/ReviewController.java
  server/src/main/java/com/hexacore/tayo/review/ReviewService.java
  server/src/main/java/com/hexacore/tayo/review/dto/CreateReviewRequestDto.java
  server/src/main/java/com/hexacore/tayo/review/dto/GetCarReviewsResponseDto.java
  server/src/main/java/com/hexacore/tayo/review/model/CarReview.java
  server/src/main/java/com/hexacore/tayo/review/model/CarReviewRepository.java
  server/src/main/java/com/hexacore/tayo/review/model/GuestReview.java
  server/src/main/java/com/hexacore/tayo/review/model/GuestReviewRepository.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
  server/src/main/resources/log4j2.xml
Labels: BE, feat

#232 [BE] HOTFIX: .gitignore에 log 폴더 추가
  server/.gitignore
Labels: bug, BE, urgent

#235 [BE] #151 : 차량 조회 DTO 알고리즘 개선
  server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
Labels: BE, refactor

#236 [BE] #227: 확장성을 위한 SSE 기능 추상화
  client/src/pages/auth/Login.tsx
  server/src/main/java/com/hexacore/tayo/config/AppConfig.java
  server/src/main/java/com/hexacore/tayo/notification/manager/InMemoryNotificationManager.java
  server/src/main/java/com/hexacore/tayo/notification/manager/NotificationManager.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: BE, feat

#233 [FE] #164: 리뷰 작성 페이지 구현
  client/src/components/ListComponent.tsx
  client/src/components/TimePicker.tsx
  client/src/components/Toast.tsx
  client/src/components/review/Review.tsx
  client/src/components/review/ReviewModal.tsx
  client/src/components/review/StarIcon.tsx
  client/src/components/review/StarRating.tsx
  client/src/fetches/cars/cars.type.ts
  client/src/fetches/cars/fetchCarDetail.ts
  client/src/fetches/categories/fetchCategories.ts
  client/src/fetches/common/response.type.ts
  client/src/fetches/reservations/Reservation.type.ts
  client/src/fetches/reservations/fetchGuestReservations.ts
  client/src/fetches/reservations/fetchHostReservations.ts
  client/src/fetches/reviews/Review.type.ts
  client/src/fetches/reviews/fetchReviews.ts
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/cars/ImageInfo.tsx
  client/src/pages/cars/carRoutes.tsx
  client/src/pages/cars/components/PaymentModal.tsx
  client/src/pages/home/components/CarCard.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/hosts/HostRegister.tsx
  client/src/pages/hosts/hostsRoutes.tsx
  client/src/pages/profile/Profile.tsx
  client/src/pages/profile/profileRoutes.tsx
  client/src/utils/converters.ts
Labels: FE, feat

#240 hotfix: 에러 발생하는 테스트 코드 삭제
  server/src/test/java/com/hexacore/tayo/car/CarControllerTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceRetrieveCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceUpdateDatesTest.java
Labels: BE

#242 [BE] #224: 차량 등록, 삭제, 카테고리 조회, 결제 관련 API 리팩토링 및 테스트 코드 수정
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/category/CategoryCustomRepository.java
  server/src/main/java/com/hexacore/tayo/category/CategoryCustomRepositoryImpl.java
  server/src/main/java/com/hexacore/tayo/category/CategoryRepository.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/util/S3Manager.java
  server/src/test/java/com/hexacore/tayo/TestConfig.java
  server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
  server/src/test/java/com/hexacore/tayo/category/CategoryRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/category/CategoryServiceTest.java
Labels: BE, refactor

#244 [FE] #111 : 프론트엔드 배포 파이프라인 구축
  .github/workflows/fe-vite.yml
Labels: FE, refactor

#247 [BE] HOTFIX: S3 Manager 파일 명에서 유효하지 않은 확장자명이 들어가는 버그 수정
  server/src/main/java/com/hexacore/tayo/util/S3Manager.java
Labels: bug, BE, urgent

#251 [FE] hotfix: baseURL이 기본값인 부분 수정
  client/.env.example
  client/.gitignore
  client/src/components/notification/NotificationBox.tsx
  client/src/fetches/common/axios.ts
Labels: bug, FE

#254 [FE, BE] HOTFIX: 알림 전송 상대 변경, jwt 에러 메제지 두 번 뜨는 버그 해결
  client/src/fetches/common/axios.ts
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: bug, FE, BE

#250 [FE, BE] HOTFIX: 금액이 음수가 되고 음수일 때 예약 되는 버그
  client/src/components/ListComponent.tsx
  client/src/components/Toast.tsx
  client/src/components/review/ReviewModal.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/cars/components/PaymentModal.tsx
  client/src/pages/hosts/HostManage.tsx
  client/src/pages/payment/Payment.tsx
  client/src/pages/profile/Profile.tsx
  server/src/main/java/com/hexacore/tayo/user/model/User.java
Labels: bug, FE

#257 [FE] #256: 차량 등록/수정 페이지에서 서버 연결이 안될 경우에도 렌더링되도록 수정
  client/src/pages/hosts/HostRegister.tsx
  client/src/pages/hosts/hostsRoutes.tsx
Labels: FE, feat

#249 [BE] #210: 예약 관련 세 가지 상황에 대한 동시성 문제 해결
  server/build.gradle
  server/src/main/java/com/hexacore/tayo/auth/AuthService.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/carRepository/CarRepository.java
  server/src/main/java/com/hexacore/tayo/car/carRepository/CustomCarRepository.java
  server/src/main/java/com/hexacore/tayo/car/carRepository/CustomCarRepositoryImpl.java
  server/src/main/java/com/hexacore/tayo/car/model/Car.java
  server/src/main/java/com/hexacore/tayo/car/model/CarDateRange.java
  server/src/main/java/com/hexacore/tayo/common/errors/ErrorCode.java
  server/src/main/java/com/hexacore/tayo/config/AppConfig.java
  server/src/main/java/com/hexacore/tayo/lock/InMemoryRangeLockManager.java
  server/src/main/java/com/hexacore/tayo/lock/LockKeyGenerator.java
  server/src/main/java/com/hexacore/tayo/lock/RangeLockManager.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationController.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationRepository.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
  server/src/main/java/com/hexacore/tayo/review/ReviewService.java
  server/src/main/java/com/hexacore/tayo/user/UserService.java
  server/src/main/java/com/hexacore/tayo/user/model/User.java
  server/src/test/java/com/hexacore/tayo/car/CarRepositoryTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
Labels: BE, feat

#261 [FE] #259: Pre-signed URL 적용
  client/.env.example
  client/src/fetches/cars/cars.type.ts
  client/src/fetches/cars/fetchCars.ts
  client/src/fetches/categories/fetchCategories.ts
  client/src/pages/home/Home.tsx
  client/src/pages/home/homeRoutes.tsx
  client/src/pages/hosts/HostRegister.tsx
  client/src/utils/ImageManger.ts
Labels: FE, feat

#262 [BE] #259: Pre-signed URL 적용
  server/src/main/java/com/hexacore/tayo/car/CarController.java
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/car/dto/CreateCarRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetPresignedUrlsRequestDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/GetPresignedUrlsResposneDto.java
  server/src/main/java/com/hexacore/tayo/car/dto/UpdateCarRequestDto.java
  server/src/main/java/com/hexacore/tayo/util/S3Manager.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceCreateCarTest.java
  server/src/test/java/com/hexacore/tayo/car/CarServiceDeleteCarTest.java
Labels: BE, feat

#267 [BE] hotfix: 백엔드 배포 브랜치 deploy-BE로 변경
  .github/workflows/be-gradle.yml
Labels: BE, urgent

#268 [FE] 프론트 배포 진행
  .github/workflows/be-gradle.yml
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/home/components/sidebar/SideBar.tsx
  client/src/pages/payment/Payment.tsx
  client/src/pages/payment/paymentRoutes.tsx
  client/tailwind.config.js
Labels: FE

#271 [BE] refactor: 검색 API 여러 종류의 차 종류 선택 가능 하도록 수정, 예약 된 구간 검색되는 버그 수정
  server/src/main/java/com/hexacore/tayo/car/carRepository/CustomCarRepositoryImpl.java
  server/src/main/java/com/hexacore/tayo/car/dto/SearchCarsDto.java
Labels: bug, BE, refactor

#274 [FE] #253: UX 개선을 위한 확인 모달과 토스트 메세지 추가
  client/src/components/CheckModal.tsx
  client/src/components/Header.tsx
  client/src/components/ListComponent.tsx
  client/src/components/Toast.tsx
  client/src/components/notification/NotificationBox.tsx
  client/src/components/notification/NotificationItem.tsx
  client/src/components/review/Review.tsx
  client/src/components/review/StarIcon.tsx
  client/src/components/svgs/CloseIcon.tsx
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/cars/ImageInfo.tsx
  client/src/pages/cars/components/PaymentModal.tsx
  client/src/pages/home/components/Map.tsx
  client/src/pages/profile/Profile.tsx
  server/src/main/java/com/hexacore/tayo/config/AppConfig.java
Labels: FE, feat

#275 [FE] HOTFIX: 결제 모달 차넘버 하드코딩, 검색 API 파라미터 명 오류 수정
  client/src/fetches/cars/fetchCars.ts
  client/src/pages/cars/CarDetail.tsx
  client/src/pages/cars/components/PaymentModal.tsx
Labels: FE, urgent

#278 [FE] #277: 검색 화면에서 필터링 적용이 되지 않는 이슈
  client/src/pages/home/components/sidebar/SideBar.tsx
Labels: bug, FE

#276 [BE] #210: 범위 락 취득, 해제 메서드 이름 수정
  server/src/main/java/com/hexacore/tayo/car/CarService.java
  server/src/main/java/com/hexacore/tayo/lock/InMemoryRangeLockManager.java
  server/src/main/java/com/hexacore/tayo/lock/LockKeyGenerator.java
  server/src/main/java/com/hexacore/tayo/lock/RangeLockManager.java
  server/src/main/java/com/hexacore/tayo/reservation/ReservationService.java
Labels: BE, refactor

#280 [README] 리드미 업데이트
  README.md
Labels: docs

#281 [README] 리드미 업데이트
  README.md
Labels: docs

#282 [README] erd 테이블 사진 수정
  README.md
Labels: docs

#283 [README] 리드미 API 명세서 업데이트
  README.md
Labels: docs
